### ISSUE TITLE
Improve endpoint validation

### ISSUE THREAD

**Issue by benijo** [apitte/core#72]
As @mabar said, we should validate endpoints not only annotations.

https://github.com/apitte/core/pull/71#discussion_r251104853

**Comment by mabar** [comment]
Note to self:
- RequestValidation and ResponseValidation
- ?? could be Request and Response merged with RequestMapper and ResponseMapper?

**Comment by mabar** [comment]
Well... my fault. Validations should be implemented in schema instead of annotations. But responses with same format could currently happen only in annotations thanks to [that](https://github.com/apitte/core/blob/4bf882f709c871c1233dc6344114e0c04a583a4f/src/Schema/Builder/Controller/Method.php#L167). Not sure if it should be changed so closing for now
